// THIS FILE IS GENERATED BY Localization.cs, add new textIds via the Localization scriptable object in Resources!

using System.Collections.Generic;

namespace LightItUp.Data
{
    public static class TextIds {
        public const string Game_Progress = "Game_Progress";
        public const string Game_CurrenLevel = "Game_CurrenLevel";

        public static List<string> allIds = new List<string>() {
            "",
            "Game_Progress",
            "Game_CurrenLevel",
        };
    }
}
