// THIS FILE IS GENERATED BY SoundManager.cs, add new music via the SoundManager prefab in Resources/Singletons!

using System.Collections.Generic;

namespace LightItUp.Sound
{
    public static class MusicNames {
        public const string BGMusic = "BGMusic";

        public static List<string> allIds = new List<string>() {
            "",
            "BGMusic",
        };
    }
}
