// THIS FILE IS GENERATED BY SoundManager.cs, add new soundNames via the SoundManager prefab in Resources/Singletons!

using System.Collections.Generic;

namespace LightItUp.Sound
{
    public static class SoundNames {
        public const string G3 = "G3";
        public const string A3 = "A3";
        public const string B3 = "B3";
        public const string C4 = "C4";
        public const string D4 = "D4";
        public const string E4 = "E4";
        public const string F4 = "F4";
        public const string G4 = "G4";
        public const string A4 = "A4";
        public const string B4 = "B4";
        public const string C5 = "C5";
        public const string D5 = "D5";
        public const string E5 = "E5";
        public const string G5 = "G5";
        public const string PopupOpen = "PopupOpen";
        public const string PopupClose = "PopupClose";

        public static List<string> allIds = new List<string>() {
            "",
            "G3",
            "A3",
            "B3",
            "C4",
            "D4",
            "E4",
            "F4",
            "G4",
            "A4",
            "B4",
            "C5",
            "D5",
            "E5",
            "G5",
            "PopupOpen",
            "PopupClose",
        };
    }
}
